name: tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event) }}'
      - run: |
          ELASTIC_APM_NODE_VERSION="v$(jq -r '.dependencies."elastic-apm-node".version' package-lock.json)"
          
          # if the version does not exist
          if [[ ! $(git tag -l "${ELASTIC_APM_NODE_VERSION}") ]]; then
            git tag ${ELASTIC_APM_NODE_VERSION}
            git push "refs/tags/${ELASTIC_APM_NODE_VERSION}"
          fi
          
